from tkinter import *
from tkinter import messagebox
from PIL import ImageTk, Image

'''
Function that creates variables according to the no. of images.
I couldn't figure out a better way to do this. If you have a better method, email me :- ireshayashas50@gmail.com

'''

def image_create(img_num, path_list):
	img_num = int(img_num) # Counts the number of images
	img_list = []
	if img_num == 1:
		try:
			img1 = ImageTk.PhotoImage(Image.open(path_list[0]))
			img_list.append(img1)
		except AttributeError:
			messagebox.showerror("No Image Selected", "No Image Selected. Try Again!")
	elif img_num == 2:
		try:
			img1 = ImageTk.PhotoImage(Image.open(path_list[0]))
			img2 = ImageTk.PhotoImage(Image.open(path_list[1]))
			img_list.append(img1)
			img_list.append(img2)
		except AttributeError:
			messagebox.showerror("No Image Selected", "No Image Selected. Try Again!")
	elif img_num == 3:
		try:
			img1 = ImageTk.PhotoImage(Image.open(path_list[0]))
			img2 = ImageTk.PhotoImage(Image.open(path_list[1]))
			img3 = ImageTk.PhotoImage(Image.open(path_list[2]))
			img_list.append(img1)
			img_list.append(img2)
			img_list.append(img3)
		except AttributeError:
			messagebox.showerror("No Image Selected", "No Image Selected. Try Again!")
	elif img_num == 4:
		try:
			img1 = ImageTk.PhotoImage(Image.open(path_list[0]))
			img2 = ImageTk.PhotoImage(Image.open(path_list[1]))
			img3 = ImageTk.PhotoImage(Image.open(path_list[2]))
			img4 = ImageTk.PhotoImage(Image.open(path_list[3]))
			img_list.append(img1)
			img_list.append(img2)
			img_list.append(img3)
			img_list.append(img4)
		except AttributeError:
			messagebox.showerror("No Image Selected", "No Image Selected. Try Again!")
	elif img_num == 5:
		try:
			img1 = ImageTk.PhotoImage(Image.open(path_list[0]))
			img2 = ImageTk.PhotoImage(Image.open(path_list[1]))
			img3 = ImageTk.PhotoImage(Image.open(path_list[2]))
			img4 = ImageTk.PhotoImage(Image.open(path_list[3]))
			img5 = ImageTk.PhotoImage(Image.open(path_list[4]))
			img_list.append(img1)
			img_list.append(img2)
			img_list.append(img3)
			img_list.append(img4)
			img_list.append(img5)
		except AttributeError:
			messagebox.showerror("No Image Selected", "No Image Selected. Try Again!")
	elif img_num == 6:
		try:
			img1 = ImageTk.PhotoImage(Image.open(path_list[0]))
			img2 = ImageTk.PhotoImage(Image.open(path_list[1]))
			img3 = ImageTk.PhotoImage(Image.open(path_list[2]))
			img4 = ImageTk.PhotoImage(Image.open(path_list[3]))
			img5 = ImageTk.PhotoImage(Image.open(path_list[4]))
			img6 = ImageTk.PhotoImage(Image.open(path_list[5]))
			img_list.append(img1)
			img_list.append(img2)
			img_list.append(img3)
			img_list.append(img4)
			img_list.append(img5)
			img_list.append(img6)
		except AttributeError:
			messagebox.showerror("No Image Selected", "No Image Selected. Try Again!")
	elif img_num == 7:
		try:
			img1 = ImageTk.PhotoImage(Image.open(path_list[0]))
			img2 = ImageTk.PhotoImage(Image.open(path_list[1]))
			img3 = ImageTk.PhotoImage(Image.open(path_list[2]))
			img4 = ImageTk.PhotoImage(Image.open(path_list[3]))
			img5 = ImageTk.PhotoImage(Image.open(path_list[4]))
			img6 = ImageTk.PhotoImage(Image.open(path_list[5]))
			img7 = ImageTk.PhotoImage(Image.open(path_list[6]))
			img_list.append(img1)
			img_list.append(img2)
			img_list.append(img3)
			img_list.append(img4)
			img_list.append(img5)
		except AttributeError:
			messagebox.showerror("No Image Selected", "No Image Selected. Try Again!")
	elif img_num == 8:
		try:
			img1 = ImageTk.PhotoImage(Image.open(path_list[0]))
			img2 = ImageTk.PhotoImage(Image.open(path_list[1]))
			img3 = ImageTk.PhotoImage(Image.open(path_list[2]))
			img4 = ImageTk.PhotoImage(Image.open(path_list[3]))
			img5 = ImageTk.PhotoImage(Image.open(path_list[4]))
			img6 = ImageTk.PhotoImage(Image.open(path_list[5]))
			img7 = ImageTk.PhotoImage(Image.open(path_list[6]))
			img8 = ImageTk.PhotoImage(Image.open(path_list[7]))
			img_list.append(img1)
			img_list.append(img2)
			img_list.append(img3)
			img_list.append(img4)
			img_list.append(img5)
			img_list.append(img6)
			img_list.append(img7)
			img_list.append(img8)
		except AttributeError:
			messagebox.showerror("No Image Selected", "No Image Selected. Try Again!")
	elif img_num == 8:
		try:
			img1 = ImageTk.PhotoImage(Image.open(path_list[0]))
			img2 = ImageTk.PhotoImage(Image.open(path_list[1]))
			img3 = ImageTk.PhotoImage(Image.open(path_list[2]))
			img4 = ImageTk.PhotoImage(Image.open(path_list[3]))
			img5 = ImageTk.PhotoImage(Image.open(path_list[4]))
			img6 = ImageTk.PhotoImage(Image.open(path_list[5]))
			img7 = ImageTk.PhotoImage(Image.open(path_list[6]))
			img8 = ImageTk.PhotoImage(Image.open(path_list[7]))
			img_list.append(img1)
			img_list.append(img2)
			img_list.append(img3)
			img_list.append(img4)
			img_list.append(img5)
			img_list.append(img6)
			img_list.append(img7)
			img_list.append(img8)
		except AttributeError:
			messagebox.showerror("No Image Selected", "No Image Selected. Try Again!")
	elif img_num == 9:
		try:
			img1 = ImageTk.PhotoImage(Image.open(path_list[0]))
			img2 = ImageTk.PhotoImage(Image.open(path_list[1]))
			img3 = ImageTk.PhotoImage(Image.open(path_list[2]))
			img4 = ImageTk.PhotoImage(Image.open(path_list[3]))
			img5 = ImageTk.PhotoImage(Image.open(path_list[4]))
			img6 = ImageTk.PhotoImage(Image.open(path_list[5]))
			img7 = ImageTk.PhotoImage(Image.open(path_list[6]))
			img8 = ImageTk.PhotoImage(Image.open(path_list[7]))
			img9 = ImageTk.PhotoImage(Image.open(path_list[8]))
			img_list.append(img1)
			img_list.append(img2)
			img_list.append(img3)
			img_list.append(img4)
			img_list.append(img5)
			img_list.append(img6)
			img_list.append(img7)
			img_list.append(img8)
			img_list.append(img9)
		except AttributeError:
			messagebox.showerror("No Image Selected", "No Image Selected. Try Again!")
	elif img_num == 10:
		try:
			img1 = ImageTk.PhotoImage(Image.open(path_list[0]))
			img2 = ImageTk.PhotoImage(Image.open(path_list[1]))
			img3 = ImageTk.PhotoImage(Image.open(path_list[2]))
			img4 = ImageTk.PhotoImage(Image.open(path_list[3]))
			img5 = ImageTk.PhotoImage(Image.open(path_list[4]))
			img6 = ImageTk.PhotoImage(Image.open(path_list[5]))
			img7 = ImageTk.PhotoImage(Image.open(path_list[6]))
			img8 = ImageTk.PhotoImage(Image.open(path_list[7]))
			img9 = ImageTk.PhotoImage(Image.open(path_list[8]))
			img10 = ImageTk.PhotoImage(Image.open(path_list[9]))
			img_list.append(img1)
			img_list.append(img2)
			img_list.append(img3)
			img_list.append(img4)
			img_list.append(img5)
			img_list.append(img6)
			img_list.append(img7)
			img_list.append(img8)
			img_list.append(img9)
			img_list.append(img10)
		except AttributeError:
			messagebox.showerror("No Image Selected", "No Image Selected. Try Again!")
	elif img_num == 11:
		try:
			img1 = ImageTk.PhotoImage(Image.open(path_list[0]))
			img2 = ImageTk.PhotoImage(Image.open(path_list[1]))
			img3 = ImageTk.PhotoImage(Image.open(path_list[2]))
			img4 = ImageTk.PhotoImage(Image.open(path_list[3]))
			img5 = ImageTk.PhotoImage(Image.open(path_list[4]))
			img6 = ImageTk.PhotoImage(Image.open(path_list[5]))
			img7 = ImageTk.PhotoImage(Image.open(path_list[6]))
			img8 = ImageTk.PhotoImage(Image.open(path_list[7]))
			img9 = ImageTk.PhotoImage(Image.open(path_list[8]))
			img10 = ImageTk.PhotoImage(Image.open(path_list[9]))
			img11 = ImageTk.PhotoImage(Image.open(path_list[10]))
			img_list.append(img1)
			img_list.append(img2)
			img_list.append(img3)
			img_list.append(img4)
			img_list.append(img5)
			img_list.append(img6)
			img_list.append(img7)
			img_list.append(img8)
			img_list.append(img9)
			img_list.append(img10)
			img_list.append(img11)
		except AttributeError:
			messagebox.showerror("No Image Selected", "No Image Selected. Try Again!")
	elif img_num == 12:
		try:
			img1 = ImageTk.PhotoImage(Image.open(path_list[0]))
			img2 = ImageTk.PhotoImage(Image.open(path_list[1]))
			img3 = ImageTk.PhotoImage(Image.open(path_list[2]))
			img4 = ImageTk.PhotoImage(Image.open(path_list[3]))
			img5 = ImageTk.PhotoImage(Image.open(path_list[4]))
			img6 = ImageTk.PhotoImage(Image.open(path_list[5]))
			img7 = ImageTk.PhotoImage(Image.open(path_list[6]))
			img8 = ImageTk.PhotoImage(Image.open(path_list[7]))
			img9 = ImageTk.PhotoImage(Image.open(path_list[8]))
			img10 = ImageTk.PhotoImage(Image.open(path_list[9]))
			img11 = ImageTk.PhotoImage(Image.open(path_list[10]))
			img12 = ImageTk.PhotoImage(Image.open(path_list[11]))
			img_list.append(img1)
			img_list.append(img2)
			img_list.append(img3)
			img_list.append(img4)
			img_list.append(img5)
			img_list.append(img6)
			img_list.append(img7)
			img_list.append(img8)
			img_list.append(img9)
			img_list.append(img10)
			img_list.append(img11)
			img_list.append(img12)
		except AttributeError:
			messagebox.showerror("No Image Selected", "No Image Selected. Try Again!")
	elif img_num == 13:
		try:
			img1 = ImageTk.PhotoImage(Image.open(path_list[0]))
			img2 = ImageTk.PhotoImage(Image.open(path_list[1]))
			img3 = ImageTk.PhotoImage(Image.open(path_list[2]))
			img4 = ImageTk.PhotoImage(Image.open(path_list[3]))
			img5 = ImageTk.PhotoImage(Image.open(path_list[4]))
			img6 = ImageTk.PhotoImage(Image.open(path_list[5]))
			img7 = ImageTk.PhotoImage(Image.open(path_list[6]))
			img8 = ImageTk.PhotoImage(Image.open(path_list[7]))
			img9 = ImageTk.PhotoImage(Image.open(path_list[8]))
			img10 = ImageTk.PhotoImage(Image.open(path_list[9]))
			img11 = ImageTk.PhotoImage(Image.open(path_list[10]))
			img12 = ImageTk.PhotoImage(Image.open(path_list[11]))
			img13 = ImageTk.PhotoImage(Image.open(path_list[12]))
			img_list.append(img1)
			img_list.append(img2)
			img_list.append(img3)
			img_list.append(img4)
			img_list.append(img5)
			img_list.append(img6)
			img_list.append(img7)
			img_list.append(img8)
			img_list.append(img9)
			img_list.append(img10)
			img_list.append(img11)
			img_list.append(img12)
			img_list.append(img13)
		except AttributeError:
			messagebox.showerror("No Image Selected", "No Image Selected. Try Again!")
	elif img_num == 14:
		try:
			img1 = ImageTk.PhotoImage(Image.open(path_list[0]))
			img2 = ImageTk.PhotoImage(Image.open(path_list[1]))
			img3 = ImageTk.PhotoImage(Image.open(path_list[2]))
			img4 = ImageTk.PhotoImage(Image.open(path_list[3]))
			img5 = ImageTk.PhotoImage(Image.open(path_list[4]))
			img6 = ImageTk.PhotoImage(Image.open(path_list[5]))
			img7 = ImageTk.PhotoImage(Image.open(path_list[6]))
			img8 = ImageTk.PhotoImage(Image.open(path_list[7]))
			img9 = ImageTk.PhotoImage(Image.open(path_list[8]))
			img10 = ImageTk.PhotoImage(Image.open(path_list[9]))
			img11 = ImageTk.PhotoImage(Image.open(path_list[10]))
			img12 = ImageTk.PhotoImage(Image.open(path_list[11]))
			img13 = ImageTk.PhotoImage(Image.open(path_list[12]))
			img14 = ImageTk.PhotoImage(Image.open(path_list[13]))
			img_list.append(img1)
			img_list.append(img2)
			img_list.append(img3)
			img_list.append(img4)
			img_list.append(img5)
			img_list.append(img6)
			img_list.append(img7)
			img_list.append(img8)
			img_list.append(img9)
			img_list.append(img10)
			img_list.append(img11)
			img_list.append(img12)
			img_list.append(img13)
			img_list.append(img14)
		except AttributeError:
			messagebox.showerror("No Image Selected", "No Image Selected. Try Again!")
	elif img_num == 15:
		try:
			img1 = ImageTk.PhotoImage(Image.open(path_list[0]))
			img2 = ImageTk.PhotoImage(Image.open(path_list[1]))
			img3 = ImageTk.PhotoImage(Image.open(path_list[2]))
			img4 = ImageTk.PhotoImage(Image.open(path_list[3]))
			img5 = ImageTk.PhotoImage(Image.open(path_list[4]))
			img6 = ImageTk.PhotoImage(Image.open(path_list[5]))
			img7 = ImageTk.PhotoImage(Image.open(path_list[6]))
			img8 = ImageTk.PhotoImage(Image.open(path_list[7]))
			img9 = ImageTk.PhotoImage(Image.open(path_list[8]))
			img10 = ImageTk.PhotoImage(Image.open(path_list[9]))
			img11 = ImageTk.PhotoImage(Image.open(path_list[10]))
			img12 = ImageTk.PhotoImage(Image.open(path_list[11]))
			img13 = ImageTk.PhotoImage(Image.open(path_list[12]))
			img14 = ImageTk.PhotoImage(Image.open(path_list[13]))
			img15 = ImageTk.PhotoImage(Image.open(path_list[14]))
			img_list.append(img1)
			img_list.append(img2)
			img_list.append(img3)
			img_list.append(img4)
			img_list.append(img5)
			img_list.append(img6)
			img_list.append(img7)
			img_list.append(img8)
			img_list.append(img9)
			img_list.append(img10)
			img_list.append(img11)
			img_list.append(img12)
			img_list.append(img13)
			img_list.append(img14)
			img_list.append(img15)
		except AttributeError:
			messagebox.showerror("No Image Selected", "No Image Selected. Try Again!")
	elif img_num == 16:
		try:
			img1 = ImageTk.PhotoImage(Image.open(path_list[0]))
			img2 = ImageTk.PhotoImage(Image.open(path_list[1]))
			img3 = ImageTk.PhotoImage(Image.open(path_list[2]))
			img4 = ImageTk.PhotoImage(Image.open(path_list[3]))
			img5 = ImageTk.PhotoImage(Image.open(path_list[4]))
			img6 = ImageTk.PhotoImage(Image.open(path_list[5]))
			img7 = ImageTk.PhotoImage(Image.open(path_list[6]))
			img8 = ImageTk.PhotoImage(Image.open(path_list[7]))
			img9 = ImageTk.PhotoImage(Image.open(path_list[8]))
			img10 = ImageTk.PhotoImage(Image.open(path_list[9]))
			img11 = ImageTk.PhotoImage(Image.open(path_list[10]))
			img12 = ImageTk.PhotoImage(Image.open(path_list[11]))
			img13 = ImageTk.PhotoImage(Image.open(path_list[12]))
			img14 = ImageTk.PhotoImage(Image.open(path_list[13]))
			img15 = ImageTk.PhotoImage(Image.open(path_list[14]))
			img16 = ImageTk.PhotoImage(Image.open(path_list[15]))
			img_list.append(img1)
			img_list.append(img2)
			img_list.append(img3)
			img_list.append(img4)
			img_list.append(img5)
			img_list.append(img6)
			img_list.append(img7)
			img_list.append(img8)
			img_list.append(img9)
			img_list.append(img10)
			img_list.append(img11)
			img_list.append(img12)
			img_list.append(img13)
			img_list.append(img14)
			img_list.append(img15)
			img_list.append(img16)
		except AttributeError:
			messagebox.showerror("No Image Selected", "No Image Selected. Try Again!")
	elif img_num == 17:
		try:
			img1 = ImageTk.PhotoImage(Image.open(path_list[0]))
			img2 = ImageTk.PhotoImage(Image.open(path_list[1]))
			img3 = ImageTk.PhotoImage(Image.open(path_list[2]))
			img4 = ImageTk.PhotoImage(Image.open(path_list[3]))
			img5 = ImageTk.PhotoImage(Image.open(path_list[4]))
			img6 = ImageTk.PhotoImage(Image.open(path_list[5]))
			img7 = ImageTk.PhotoImage(Image.open(path_list[6]))
			img8 = ImageTk.PhotoImage(Image.open(path_list[7]))
			img9 = ImageTk.PhotoImage(Image.open(path_list[8]))
			img10 = ImageTk.PhotoImage(Image.open(path_list[9]))
			img11 = ImageTk.PhotoImage(Image.open(path_list[10]))
			img12 = ImageTk.PhotoImage(Image.open(path_list[11]))
			img13 = ImageTk.PhotoImage(Image.open(path_list[12]))
			img14 = ImageTk.PhotoImage(Image.open(path_list[13]))
			img15 = ImageTk.PhotoImage(Image.open(path_list[14]))
			img16 = ImageTk.PhotoImage(Image.open(path_list[15]))
			img17 = ImageTk.PhotoImage(Image.open(path_list[16]))
			img_list.append(img1)
			img_list.append(img2)
			img_list.append(img3)
			img_list.append(img4)
			img_list.append(img5)
			img_list.append(img6)
			img_list.append(img7)
			img_list.append(img8)
			img_list.append(img9)
			img_list.append(img10)
			img_list.append(img11)
			img_list.append(img12)
			img_list.append(img13)
			img_list.append(img14)
			img_list.append(img15)
			img_list.append(img16)
			img_list.append(img17)
		except AttributeError:
			messagebox.showerror("No Image Selected", "No Image Selected. Try Again!")
	elif img_num == 18:
		try:
			img1 = ImageTk.PhotoImage(Image.open(path_list[0]))
			img2 = ImageTk.PhotoImage(Image.open(path_list[1]))
			img3 = ImageTk.PhotoImage(Image.open(path_list[2]))
			img4 = ImageTk.PhotoImage(Image.open(path_list[3]))
			img5 = ImageTk.PhotoImage(Image.open(path_list[4]))
			img6 = ImageTk.PhotoImage(Image.open(path_list[5]))
			img7 = ImageTk.PhotoImage(Image.open(path_list[6]))
			img8 = ImageTk.PhotoImage(Image.open(path_list[7]))
			img9 = ImageTk.PhotoImage(Image.open(path_list[8]))
			img10 = ImageTk.PhotoImage(Image.open(path_list[9]))
			img11 = ImageTk.PhotoImage(Image.open(path_list[10]))
			img12 = ImageTk.PhotoImage(Image.open(path_list[11]))
			img13 = ImageTk.PhotoImage(Image.open(path_list[12]))
			img14 = ImageTk.PhotoImage(Image.open(path_list[13]))
			img15 = ImageTk.PhotoImage(Image.open(path_list[14]))
			img16 = ImageTk.PhotoImage(Image.open(path_list[15]))
			img17 = ImageTk.PhotoImage(Image.open(path_list[16]))
			img18 = ImageTk.PhotoImage(Image.open(path_list[17]))
			img_list.append(img1)
			img_list.append(img2)
			img_list.append(img3)
			img_list.append(img4)
			img_list.append(img5)
			img_list.append(img6)
			img_list.append(img7)
			img_list.append(img8)
			img_list.append(img9)
			img_list.append(img10)
			img_list.append(img11)
			img_list.append(img12)
			img_list.append(img13)
			img_list.append(img14)
			img_list.append(img15)
			img_list.append(img16)
			img_list.append(img17)
			img_list.append(img18)
		except AttributeError:
			messagebox.showerror("No Image Selected", "No Image Selected. Try Again!")
	elif img_num == 19:
		try:
			img1 = ImageTk.PhotoImage(Image.open(path_list[0]))
			img2 = ImageTk.PhotoImage(Image.open(path_list[1]))
			img3 = ImageTk.PhotoImage(Image.open(path_list[2]))
			img4 = ImageTk.PhotoImage(Image.open(path_list[3]))
			img5 = ImageTk.PhotoImage(Image.open(path_list[4]))
			img6 = ImageTk.PhotoImage(Image.open(path_list[5]))
			img7 = ImageTk.PhotoImage(Image.open(path_list[6]))
			img8 = ImageTk.PhotoImage(Image.open(path_list[7]))
			img9 = ImageTk.PhotoImage(Image.open(path_list[8]))
			img10 = ImageTk.PhotoImage(Image.open(path_list[9]))
			img11 = ImageTk.PhotoImage(Image.open(path_list[10]))
			img12 = ImageTk.PhotoImage(Image.open(path_list[11]))
			img13 = ImageTk.PhotoImage(Image.open(path_list[12]))
			img14 = ImageTk.PhotoImage(Image.open(path_list[13]))
			img15 = ImageTk.PhotoImage(Image.open(path_list[14]))
			img16 = ImageTk.PhotoImage(Image.open(path_list[15]))
			img17 = ImageTk.PhotoImage(Image.open(path_list[16]))
			img18 = ImageTk.PhotoImage(Image.open(path_list[17]))
			img19 = ImageTk.PhotoImage(Image.open(path_list[18]))
			img_list.append(img1)
			img_list.append(img2)
			img_list.append(img3)
			img_list.append(img4)
			img_list.append(img5)
			img_list.append(img6)
			img_list.append(img7)
			img_list.append(img8)
			img_list.append(img9)
			img_list.append(img10)
			img_list.append(img11)
			img_list.append(img12)
			img_list.append(img13)
			img_list.append(img14)
			img_list.append(img15)
			img_list.append(img16)
			img_list.append(img17)
			img_list.append(img18)
			img_list.append(img19)
		except AttributeError:
			messagebox.showerror("No Image Selected", "No Image Selected. Try Again!")
	elif img_num == 20:
		try:
			img1 = ImageTk.PhotoImage(Image.open(path_list[0]))
			img2 = ImageTk.PhotoImage(Image.open(path_list[1]))
			img3 = ImageTk.PhotoImage(Image.open(path_list[2]))
			img4 = ImageTk.PhotoImage(Image.open(path_list[3]))
			img5 = ImageTk.PhotoImage(Image.open(path_list[4]))
			img6 = ImageTk.PhotoImage(Image.open(path_list[5]))
			img7 = ImageTk.PhotoImage(Image.open(path_list[6]))
			img8 = ImageTk.PhotoImage(Image.open(path_list[7]))
			img9 = ImageTk.PhotoImage(Image.open(path_list[8]))
			img10 = ImageTk.PhotoImage(Image.open(path_list[9]))
			img11 = ImageTk.PhotoImage(Image.open(path_list[10]))
			img12 = ImageTk.PhotoImage(Image.open(path_list[11]))
			img13 = ImageTk.PhotoImage(Image.open(path_list[12]))
			img14 = ImageTk.PhotoImage(Image.open(path_list[13]))
			img15 = ImageTk.PhotoImage(Image.open(path_list[14]))
			img16 = ImageTk.PhotoImage(Image.open(path_list[15]))
			img17 = ImageTk.PhotoImage(Image.open(path_list[16]))
			img18 = ImageTk.PhotoImage(Image.open(path_list[17]))
			img19 = ImageTk.PhotoImage(Image.open(path_list[18]))
			img20 = ImageTk.PhotoImage(Image.open(path_list[19]))
			img_list.append(img1)
			img_list.append(img2)
			img_list.append(img3)
			img_list.append(img4)
			img_list.append(img5)
			img_list.append(img6)
			img_list.append(img7)
			img_list.append(img8)
			img_list.append(img9)
			img_list.append(img10)
			img_list.append(img11)
			img_list.append(img12)
			img_list.append(img13)
			img_list.append(img14)
			img_list.append(img15)
			img_list.append(img16)
			img_list.append(img17)
			img_list.append(img18)
			img_list.append(img19)
			img_list.append(img20)
		except AttributeError:
			messagebox.showerror("Error", "No Image Selected. Try Again!")
	else:
		print("Error! Maximum number of images exceeded!")
	return img_list	